[[redirects]]
  from = "/*"
  to = "/#2"
  status = 301
  force = true
[[redirects]]
  from = "/#2"
  to = "https://www.canva.com/design/DAEauePzST4/9UIf5L6BIedqK2K-A38UsQ/view?website:splat"
  status = 301
  force = true