[[redirects]]
  from = "/*"
  to = "/view?website#2"
  status = 20
  force = true
[[redirects]]
  from = "/view?website#2"
  to = "https://www.canva.com/design/DAEauePzST4/9UIf5L6BIedqK2K-A38UsQ/view?website#2"
  status = 301
  force = true